### ISSUE TITLE
Ориентация аппарата

### ISSUE THREAD

**Issue by 14droplets** [shostakovichs-spacecraft-factory/cansat-2018-2019#10]
Уже понятно что её нужно будет считать и возможно на борту

* Используем ли активное управление ориентацией?
* Какие актуаторы используем для управления ориентацией?

**Comment by 14droplets** [comment]
Варианты:

1) Не используем управление ориентацией вовсе. Рассчитываем на широкоугольный объектив и известный угол солнца
2) управляем ориентацией маховиком/маховиками
3) ~~управляем ориентацией пропеллерами~~ (при давлении в 10Па, это врятли возможно)
4) управляем ориентацией зацепившись за трос
5) управляем ориентацией газовыми _пшикалками_

**Comment by macJIuHa** [comment]
Скорее всего управляем ориентацией, зацепившись за трос
А ориентироваться я предлагаю не по показателям акселерометра/гироскопа, а по датчикам освещённости

**Comment by 14droplets** [comment]
Решено
