### ISSUE TITLE
Формирование ТЗ на аппарат и научный проект

### ISSUE THREAD

**Issue by SeresHotes** [shostakovichs-spacecraft-factory/cansat-2018-2019#15]

**Comment by 14droplets** [comment]
Наиболее интересные документы по теме:
* ГОСТ на ТЗ по космическим системам https://pdf.standartgost.ru/catalog/Data2/1/4293772/4293772029.pdf

**Comment by 14droplets** [comment]
Тз разбилось на кусочки: 2b52c6d0b880e76afe65e6e013596cadece21f3a

**Comment by SeresHotes** [comment]
Готово!
