### ISSUE TITLE
Написать описание протоколов, используемых в разрабатываемой системе 

### ISSUE THREAD

**Issue by 14droplets** [shostakovichs-spacecraft-factory/cansat-2018-2019#18]
По текущей версии документа (по состоянию на 124587e6b28e8e00db5c367e30e6984616aaf11b) есть ряд замечаний и рекомендаций.

#### 1.1 По структуре документа. 

Учитывай, что люди, которые читают его - первый раз видят все что написано и не имеют никакущего представления о том, как построена наша система. Поэтому в начале следует описать её полностью с самого начала и сверху вниз.

Начинаем с самого верхнего уровня: в системе есть несколько .... не знаю как это назвать? элементы? локации? агрегаты? Подумай... Короче в системе зонд, сервер, обменная машина (raspberry pi) и ноут в качестве автоматизированного рабочего места оператора. Кратко описываем каждый агрегат. Какие задачи решает, зачем нужен. В этом же разделе и твоя картинка.

Продолжаем - в системе определено понятие терминала - физического устройства, которое физически соединено с прочими устройствами различными шинами/интерфейсами и способно передавать/принимать сообщения от других терминалов. Перечисляем терминалы (ICU, PCU, RPI, ноут и прочие), так же кратко описываем - что из себя представляет, какие задачи решает. Так же в этом разделе следует описать какой терминал с каким общается и при помощи какого протокола низшего уровня (TCP/UDP/CAN и прочее).

Ну и наконец - в системе определены логические абоненты. Абоненты это такие логические штуки, которые существуют только виртуально и сидят в терминалах. Абоненты общаются между собой при помощи преимущественно MAVLINK-а, который проходит поверх протоколов которыми общаются терминалы. Снова перечисляем абонентов. Говорим на каком терминале они сидят, что из себя представляют, какие задачи решают. Можно для каждого абонента кратко написать какими данными, передаваемыми другими абонентами они интересуются.

Вот и все что следует написать на мой взгляд. Углубляться в перечень CAN-овских идентификаторов и MAVLINK сообщений не нужно. Во-первых не успеем, а во вторых - эскизный проект этого и не подразумевает. Можно прямо так и написать, что, например, `перечень идентификаторов CAN сообщений передаваемых терминалами определяется на этапе рабочего проекта`.

#### 1.2. По оформлению 

1.2.1. Все картинки с номерами и в тексте ссылки на них. Делаем чуток по-взрослому.

1.2.2. Все аббревиатуры должны быть развернуты в скобочках или еще как-то при первом упоминании и в конце должна быть страничка со списком сокращений.

1.2.3. Если упоминается какая-то посторонняя сущность - на нее хорошо бы сослаться. Например у нас используется CAN 2.0B (ISO 11898). Есть целая куча доков и стандарт с описанием этого CAN-а. Просто сошлись на эти доки и все: протокол описан. Тоже самое с мавлинками, уартами и прочей радостью. В конце документа страничка со ссылочной документаций, А в тексте ссылки-номера в виде [1], [2], [3] и так далее.

### 2. Замечания

Тут уже просто конкретные замечания по тексту.

2.1. Space shuttle на картинке - лишнее. У нас не шатл и не спейс. Ну и документ на русском, подписи/надписи тоже следует делать на русском (это я сейчас про ground station). При этом названия модулей имхо на енге можно - названия это авторское.

2.2. Продолжая тему схемы - сервер представлен простым квадратиком, тогда как остальные элементы системы - большими рамочками. Это вводит некоторый диссонанс. Сервер тоже следует сделать рамочкой. Внутри можно нарисовать системную службу взаимодействия с иридиумом и БД для хранения телеметрии. Рисовать можно какими-нибудь параллелепипедами или сильно другим цветом, чтобы показать это ПО а не железки.

2.3. Для иридиума хорошо бы нарисовать связь между модемом и сервером через спутник (прям картинкой вставить).

2.4. по второму абзацу - LORA это, строго говоря не протокол. Это вид модуляции. Протокол там какой-то есть, и он вроде описан в доках, но названия своего не имеет. Можно написать как, например, `определяемый производителем радиомодуля 
протокол` и сослаться на доку к модулю.

2.5.  Шестой абзац - `Данные на компьютерах аппарата ...`. Лучше перефразировать как `данные, передаваемые компьютерами аппарата будут передаваться при помощи пакетов протокола MAVLINK (ссылка на описание)`. Строка про идентификатор - лишняя. Протокол это (и многое другое) определяет сам по себе.

**Comment by SeresHotes** [comment]
Готова абсолютно новая версия. Прошу проверить.

**Comment by 14droplets** [comment]
Хорошо. Немножко поправил орфографию (f27f20f). Осталось одно замечание - не написано на каких терминалах находятся абоненты. Это необходимо указать, иначе не понятно откуда они вообще взялись
