### ISSUE TITLE
Формирование вопросов по регламенту и стратосферному полёту.

### ISSUE THREAD

**Issue by 14droplets** [shostakovichs-spacecraft-factory/cansat-2018-2019#2]
Информация из текущего регламента (http://roscansat.com/uchastnikam/polozhenie/) сильно отличается от фактического положения вещей, которые мы видели на полигоне.

Так же ожидается встреча с организаторами, к которой нужно бы подготовить список общих вопросов по стратосферному полёту: (на что обратить внимания, какая система терморегулирования предпочтительнее и т.п.)

**Comment by macJIuHa** [comment]
Можно ли использовать маховики?
Какая гарантированная высота полёта?
Какая максимальная мощность передатчика?

**Comment by 14droplets** [comment]
Какова прочность аппарата на разрыв?
Можно ли использовать баллоны высокого давления?

**Comment by 14droplets** [comment]
На каких высотах мы можем рассчитывать на более менее спокойный полет, во время которого сможем ориентировать зонд. И сколько он будет длиться?

Гарантируется ли пуск днем?

Насколько вероятен конденсат на оптических элементах зонда и насколько сильно он испортит нам жизнь?

Можно ли использовать пропеллеры для построения ориентации в стратосфере? (предварительно - "не очень")

**Comment by SeresHotes** [comment]
Какие температурные изменения будет испытывать аппарат?

**Comment by macJIuHa** [comment]
Температурные изменения будут зависеть от условий стратосферы. Самое минимальное -- -50С. Проблема в том, что дальше нас начнёт печь солнце, но с этим можно попытаться справиться при помощи фольги

**Comment by 14droplets** [comment]
Итоговый список вопросов:

1. Какой способ крепления аппарата к шару?
2. На какое расстояние разнесены аппараты?
3. Какие нагрузки необходимо выдерживать креплению
4. Какие требования к форме и размеру крепления
5. Можно ли использовать маховики?
6. Какая максимальная мощность радиопередатчика?
7. Гарантируется ли пуск днем?
8. Какие предполагаемые скорости спуска и подъема?
9. Можно ли использовать баллоны со сжатым газом?
