### ISSUE TITLE
Создание презентации zwei

### ISSUE THREAD

**Issue by 14droplets** [shostakovichs-spacecraft-factory/cansat-2018-2019#23]
Разделяем #19 на задачи для отдельных участников согласно протоколу совещания от 79c2f729dac94fe4840709d5f5db29613ffb478f

Эта долька для Кирилла! Тебе достались слайды:

* 11
* 12
* 15
* 19
* 25

**Comment by Kirs67** [comment]
Закрываем-с ишью по презентации?

**Comment by Kirs67** [comment]
Презентация прошла успешно
