### ISSUE TITLE
Создание презентации drei

### ISSUE THREAD

**Issue by 14droplets** [shostakovichs-spacecraft-factory/cansat-2018-2019#24]
Разделяем #19 на задачи для отдельных участников согласно протоколу совещания от 79c2f729dac94fe4840709d5f5db29613ffb478f

Эта долька для Сергея! Тебе достались слайды:

* 8
* 9
* 10
* 26

**Comment by SeresHotes** [comment]
Почти все готово. Работа есть по ссылке в описании
.
.
.
.
.
Описание: 
..........Ссылка [тут]

**Comment by SeresHotes** [comment]
Отвечаю. Не вирус!

> Описание:
> ..........Ссылка [тут]

**Comment by 14droplets** [comment]
Вынеси на слайды еще отдельно формулу для "модели" датчика плз, которая `value = k*A*cos(alpha)`

**Comment by 14droplets** [comment]
Если докапываться, то шрифт на схеме в презентации можно сделать побольше. Издалека будет плоховато видно такой как есть

**Comment by SeresHotes** [comment]
Готово!
