### ISSUE TITLE
Выбор радиомодуля.

### ISSUE THREAD

**Issue by 14droplets** [shostakovichs-spacecraft-factory/cansat-2018-2019#3]
Какой бы ни была миссия аппарата, нам нужно выбрать мощный радиомодуль, чтобы иметь хоть какой-то приём телеметрии.

Возможно их будет несколько? Использовать ли сотовый/спутниковый модем?

**Comment by macJIuHa** [comment]
Предлагаю в любом случае отправлять SMS с координатами. Даже если кто-то из грозди это тоже сделает, лучше перестраховаться.

**Comment by 14droplets** [comment]
Рассматриваем иридиум и модем.
Используем модем как модем? или отправляем смски? или и то и другое?

**Comment by 14droplets** [comment]
По результатам обсуждения вопрос свелся к выбору диапазона и усилителя соответствующего диапазона. Так же вопрос с иридиумом вынес в отдельную задачу #5

**Comment by 14droplets** [comment]
Решено
